version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
